relation_schema = [
    {
        "table":"companies",
        "relations":{
            "created_by":{
                "start":{
                    "table":"main_table",
                    "id":"id",
                    "label":"Company"
                },
                "end":{
                    "table":"main_table",
                    "id":"created_by_entry_id",
                    "label":"User"
                },
                "properties":[
                    {
                        "table":"main_table",
                        "col":"created",
                        "prop":"datetime",
                        "type":"datetime",
                        "index":"range"
                    }
                ],
                "reverse":"create"
            },
            "modified_by":{
                "start":{
                    "table":"main_table",
                    "id":"id",
                    "label":"Company"
                },
                "end":{
                    "table":"main_table",
                    "id":"modified_by_id",
                    "label":"User"
                },
                "properties":[
                    {
                        "table":"main_table",
                        "col":"modified",
                        "prop":"datetime",
                        "type":"datetime",
                        "index":"range"
                    }
                ],
                "reverse":"modify"
            },
        }
    },
    {
        "table":"contacts",
        "relations":{
            "created_by":{
                "start":{
                    "table":"main_table",
                    "id":"id",
                    "label":"Employee"
                },
                "end":{
                    "table":"main_table",
                    "id":"created_by_id",
                    "label":"User"
                },
                "properties":[
                    {
                        "table":"main_table",
                        "col":"created",
                        "prop":"datetime",
                        "type":"datetime",
                        "index":"range"
                    }
                ],
                "reverse":"create"
            },
            "modified_by":{
                "start":{
                    "table":"main_table",
                    "id":"id",
                    "label":"Employee"
                },
                "end":{
                    "table":"main_table",
                    "id":"modified_by_id",
                    "label":"User"
                },
                "properties":[
                    {
                        "table":"main_table",
                        "col":"modified",
                        "prop":"datetime",
                        "type":"datetime",
                        "index":"range"
                    }
                ],
                "reverse":"modify"
            },
            "work_for":{
                "start":{
                    "table":"main_table",
                    "id":"id",
                    "label":"Employee"
                },
                "end":{
                    "table":"main_table",
                    "id":"company_id",
                    "label":"Company"
                },
                "properties":[
                    {
                        "table":"main_table",
                        "col":"job_title",
                        "prop":"job_title",
                        "type":"string",
                        "index":"text",
                        "full_text_index":True
                    }
                ],
                "reverse":"have_employee"
            },
            "work_at":{
                "start":{
                    "table":"main_table",
                    "id":"id",
                    "label":"Employee"
                },
                "end":{
                    "table":"main_table",
                    "id":"office_id",
                    "label":"Office"
                },
                "reverse":"assign"
            }
        }
    },
    {
        "table":"office_addresses",
        "relations":{
            "created_by":{
                "start":{
                    "table":"main_table",
                    "id":"id",
                    "label":"Office"
                },
                "end":{
                    "table":"main_table",
                    "id":"created_by_id",
                    "label":"User"
                },
                "properties":[
                    {
                        "table":"main_table",
                        "col":"created",
                        "prop":"datetime",
                        "type":"datetime",
                        "index":"range"
                    }
                ],
                "reverse":"create"
            },
            "modified_by":{
                "start":{
                    "table":"main_table",
                    "id":"id",
                    "label":"Office"
                },
                "end":{
                    "table":"main_table",
                    "id":"modified_by_id",
                    "label":"User"
                },
                "properties":[
                    {
                        "table":"main_table",
                        "col":"modified",
                        "prop":"datetime",
                        "type":"datetime",
                        "index":"range"
                    }
                ],
                "reverse":"modify"
            },
            "belong_to":{
                "start":{
                    "table":"main_table",
                    "id":"id",
                    "label":"Office"
                },
                "end":{
                    "table":"main_table",
                    "id":"company_id",
                    "label":"Company"
                },
                "reverse":"have_office"
            }
        }
    },
    {
        "table":"contacts_users",
        "relations":{
            "have_contact":{
                "start":{
                    "table":"main_table",
                    "id":"contacts_id",
                    "label":"Employee"
                },
                "end":{
                    "table":"main_table",
                    "id":"user_id",
                    "label":"User"
                },
                "reverse":"have_contact"
            },
        }
    },
    {
        "table":"company_shareholders",
        "relations":{
            "have_share":{
                "start":{
                    "table":"main_table",
                    "id":"name",
                    "label":"Shareholder"
                },
                "end":{
                    "table":"main_table",
                    "id":"company_id",
                    "label":"Company"
                },
                "properties":[
                    {
                        "table":"main_table",
                        "col":"types",
                        "prop":"type",
                        "type":"string",
                        "index":"text",
                        "full_text_index":True
                    },
                    {
                        "table":"main_table",
                        "col":"share",
                        "prop":"share_amount",
                        "type":"long",
                        "index":"range"
                    },
                    {
                        "table":"main_table",
                        "col":"currency",
                        "prop":"currency",
                        "type":"string",
                        "index":"text",
                        "full_text_index":False
                    },
                    {
                        "table":"main_table",
                        "col":"percentage",
                        "prop":"share_percentage",
                        "type":"double",
                        "index":"range"
                    },
                    {
                        "table":"main_table",
                        "col":"total_shares",
                        "prop":"total_shares",
                        "type":"long",
                        "index":"range"
                    }
                ],
                "reverse":"have_shareholder"
            },
        }
    },
    {
        "table":"projects",
        "relations":{
            "have_project":{
                "start":{
                    "table":"main_table",
                    "id":"company_id",
                    "label":"Company"
                },
                "end":{
                    "table":"main_table",
                    "id":"id",
                    "label":"Project"
                },
                "reverse":"associated_with"
            },
            "created_by":{
                "start":{
                    "table":"main_table",
                    "id":"id",
                    "label":"Project"
                },
                "end":{
                    "table":"main_table",
                    "id":"created_by_id",
                    "label":"User"
                },
                "properties":[
                    {
                        "table":"main_table",
                        "col":"created",
                        "prop":"datetime",
                        "type":"datetime",
                        "index":"range"
                    }
                ],
                "reverse":"create"
            },
            "modified_by":{
                "start":{
                    "table":"main_table",
                    "id":"id",
                    "label":"Project"
                },
                "end":{
                    "table":"main_table",
                    "id":"modified_by_id",
                    "label":"User"
                },
                "properties":[
                    {
                        "table":"main_table",
                        "col":"modified",
                        "prop":"datetime",
                        "type":"datetime",
                        "index":"range"
                    }
                ],
                "reverse":"modify"
            },
        }
    },
    {
        "table":"projects_team_members",
        "relations":{
            "have_team_member":{
                "start":{
                    "table":"main_table",
                    "id":"projects_id",
                    "label":"Project"
                },
                "end":{
                    "table":"main_table",
                    "id":"user_id",
                    "label":"User"
                },
                "reverse":"team_member_of"
            },
        }
    },
    {
        "table":"projects_introducers",
        "relations":{
            "introduced_by":{
                "start":{
                    "table":"main_table",
                    "id":"projects_id",
                    "label":"Project"
                },
                "end":{
                    "table":"main_table",
                    "id":"user_id",
                    "label":"User"
                },
                "reverse":"introduce"
            },
        }
    },
    {
        "table":"project_buyers",
        "relations":{
            "access":{
                "start":{
                    "table":"main_table",
                    "id":"project_buyer_id",
                    "label":"Company"
                },
                "end":{
                    "table":"main_table",
                    "id":"project_id",
                    "label":"Project"
                },
                "properties":[
                    {
                        "table":"project_buyer_categories",
                        "match":[
                            [
                                ["project_buyers", "buyer_category_id"],
                                ["project_buyer_categories", "id"]
                            ]
                        ],
                        "col":"name",
                        "prop":"category",
                        "type":"string",
                        "index":"text",
                        "full_text_index":True
                    },
                    {
                        "table":"project_buyer_ranks",
                        "match":[
                            [
                                ["project_buyers", "buyer_rank_id"],
                                ["project_buyer_ranks", "id"]
                            ]
                        ],
                        "col":"name",
                        "prop":"rank",
                        "type":"string",
                        "index":"text",
                        "full_text_index":True
                    },
                    {
                        "table":"project_buyer_stages",
                        "match":[
                            [
                                ["project_buyers", "stage_id"],
                                ["project_buyer_stages", "id"]
                            ]
                        ],
                        "col":"name",
                        "prop":"stage",
                        "type":"string",
                        "index":"text",
                        "full_text_index":True
                    },
                    {
                        "table":"main_table",
                        "col":"last_activity_at",
                        "prop":"last_activity_date",
                        "type":"datetime",
                        "index":"range"
                    }
                ],
                "reverse":"accessed_by"
            },
        }
    },
    {
        "table":"project_buyer_comments",
        "relations":{
            "write_comment":{
                "start":{
                    "table":"main_table",
                    "id":"created_by_id",
                    "label":"User"
                },
                "end":{
                    "table":"main_table",
                    "id":"id",
                    "label":"Project_comment"
                },
                "reverse":"written_by"
            },
            "about":{
                "start":{
                    "table":"main_table",
                    "id":"id",
                    "label":"Project_comment"
                },
                "end":{
                    "table":"project_buyers",
                    "id":"project_buyer_id",     
                    "match":[
                        [
                            ["project_buyer_comments", "project_buyer_id"],
                            ["project_buyers", "id"]
                        ]
                    ],
                    "label":"Company"
                },
                "reverse":"have_comment"
            },
            "for":{
                "start":{
                    "table":"main_table",
                    "id":"id",
                    "label":"Project_comment"
                },
                "end":{
                    "table":"main_table",
                    "id":"project_id",
                    "label":"Project"
                },
                "reverse":"have_comment"
            },
        }
    },
    {
        "table":"crm_opportunities",
        "relations":{
            "created_by":{
                "start":{
                    "table":"main_table",
                    "id":"id",
                    "label":"Opportunity"
                },
                "end":{
                    "table":"main_table",
                    "id":"created_by_id",
                    "label":"User"
                },
                "properties":[
                    {
                        "table":"main_table",
                        "col":"created",
                        "prop":"datetime",
                        "type":"datetime",
                        "index":"range"
                    }
                ],
                "reverse":"create"
            },
            "modified_by":{
                "start":{
                    "table":"main_table",
                    "id":"id",
                    "label":"Opportunity"
                },
                "end":{
                    "table":"main_table",
                    "id":"modified_by_id",
                    "label":"User"
                },
                "properties":[
                    {
                        "table":"main_table",
                        "col":"modified",
                        "prop":"datetime",
                        "type":"datetime",
                        "index":"range"
                    }
                ],
                "reverse":"modify"
            },
            "associated_with":{
                "start":{
                    "table":"main_table",
                    "id":"id",
                    "label":"Opportunity"
                },
                "end":{
                    "table":"main_table",
                    "id":"company_id",
                    "label":"Company"
                },
                "reverse":"have_opportunity"
            },
            "owned_by":{
                "start":{
                    "table":"main_table",
                    "id":"id",
                    "label":"Opportunity"
                },
                "end":{
                    "table":"main_table",
                    "id":"owner_id",
                    "label":"User"
                },
                "reverse":"own"
            },
        }
    },
    {
        "table":"crm_opportunities_contacts",
        "relations":{
            "have_contact":{
                "start":{
                    "table":"main_table",
                    "id":"opportunities_id",
                    "label":"Opportunity"
                },
                "end":{
                    "table":"main_table",
                    "id":"contacts_id",
                    "label":"Employee"
                },
                "reverse":"have_contact"
            },
        }
    },
    {
        "table":"crm_opportunities_internal_introducers",
        "relations":{
            "introduced_by":{
                "start":{
                    "table":"main_table",
                    "id":"opportunities_id",
                    "label":"Opportunity"
                },
                "end":{
                    "table":"main_table",
                    "id":"user_id",
                    "label":"User"
                },
                "reverse":"introduce"
            },
        }
    },
    {
        "table":"crm_opportunities_team_members",
        "relations":{
            "have_team_member":{
                "start":{
                    "table":"main_table",
                    "id":"opportunities_id",
                    "label":"Opportunity"
                },
                "end":{
                    "table":"main_table",
                    "id":"user_id",
                    "label":"User"
                },
                "reverse":"team_member_of"
            },
        }
    },
    {
        "table":"crm_opportunity_notes",
        "relations":{
            "write_note":{
                "start":{
                    "table":"main_table",
                    "id":"created_by_id",
                    "label":"User"
                },
                "end":{
                    "table":"main_table",
                    "id":"id",
                    "label":"Opportunity_note"
                },
                "reverse":"written_by"
            },
            "about":{
                "start":{
                    "table":"main_table",
                    "id":"id",
                    "label":"Opportunity_note"
                },
                "end":{
                    "table":"main_table",
                    "id":"opportunity_id",
                    "label":"Opportunity"
                },
                "reverse":"have_note"
            },
        }
    },
    {
        "table":"crm_opportunity_schedules",
        "relations":{
            "perform":{
                "start":{
                    "table":"main_table",
                    "id":"created_by_id",
                    "label":"User"
                },
                "end":{
                    "table":"main_table",
                    "id":"id",
                    "label":"Opportunity_activity"
                },
                "reverse":"performed_by"
            },
            "about":{
                "start":{
                    "table":"main_table",
                    "id":"id",
                    "label":"Opportunity_activity"
                },
                "end":{
                    "table":"main_table",
                    "id":"opportunity_id",
                    "label":"Opportunity"
                },
                "reverse":"have_activity"
            },
        }
    },
]